/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Bankme
 * The BankMe API description
 * OpenAPI spec version: 1.0
 */
export type UserControllerFindOneParams = {
/**
 * Parâmetros de consulta dinâmicos (enviar como um objeto JSON)
 */
query?: { [key: string]: unknown };
};

export type UserControllerFindManyParams = {
/**
 * Quantidade de itens por página
 */
limit: number;
/**
 * Número da página
 */
page: number;
};

export type AssignorControllerFindOneParams = {
/**
 * Parâmetros de consulta dinâmicos (enviar como um objeto JSON)
 */
query?: { [key: string]: unknown };
};

export type AssignorControllerFindManyParams = {
/**
 * Quantidade de itens por página
 */
take: number;
/**
 * Número da página
 */
page: number;
};

export type PayableControllerUploadFileBody = {
  file?: Blob;
};

export type PayableControllerCreateManyBody = {
  file?: Blob;
};

export type PayableControllerFindOneParams = {
/**
 * Parâmetros de consulta dinâmicos (enviar como um objeto JSON)
 */
query?: { [key: string]: unknown };
};

export type PayableControllerFindManyParams = {
/**
 * Quantidade de itens por página
 */
take: number;
/**
 * Número da página
 */
page: number;
};

export interface EmailDTO {
  message: string;
  subject: string;
  to: string;
}

export interface UserNoBaseModelDTO {
  email: string;
  password: string;
}

export interface AssignorNoBaseModelDTO {
  document: string;
  email: string;
  name: string;
  phone: string;
}

export interface PayableNoBaseModelDTO {
  assignorId: string;
  emissionDate: string;
  value: number;
}

